---
- name: install mysql from yum repo
  yum: name={{ item }} state=latest
  with_items:
    - mysql
    - mysql-server
  notify: restart mysql

- name: install required modules
  yum: name=MySQL-python state=latest

- name: ensure mysql started
  service: name=mysqld state=started enabled=yes

- name: Disallow root login remotely
  command: 'mysql -NBe "{{ item }}"'
  with_items:
    - DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')
  changed_when: False

- name: Ensure MySQL users are present.
  mysql_user:
    name: "leetcode"
    host: "localhost"
    password: "leetcode"
    priv: "*.*:ALL"
    state: present

- name: setup db
  mysql_db: name=leetcode state=present
